### PR TITLE
Added "Blue Skies"

### PR DESCRIPTION
**Pull request by chris2286266**

### CODE REVIEW

**Comment by seliqui** [comment]
Hi @chris2286266 :)
Can you share some infos about your project? (website, etc..)
We would like to have a quick look at it before merging your PR ;)

Also notice that the Collection Graphic will be displayed fairly small  displaying size will be ~6x6mm) - there's a good chance that the text you put in there wouldn't be readable.

**Comment by chris2286266** [comment]
Hi,
Ok, I will make a new PR and change the images then.
My project: Thomas knows about it, but I will also send you the info as soon as I have the landing page finished.
Cheers

**Comment by chris2286266** [comment]
Logo updated ...

**Comment by chris2286266** [comment]
Project: As more and more customers request NFTs to be developed from me (as consultant), I decided to start with a "Giveaway NFT".

Info from metadata.json: 
This is the Gnosis Edition of the 'Blue Skies NFT', created by baumann.at as a giveaway for selected customers, partners and friends. It is also intended as an experiment to allow some not extremely crypto-affine people to get a taste of the NFT universe. The smart contract of the NFT also contains a dedication feature for individual texts to the respective holders. The token is initially released on the Gnosis and Polygon chains, later possibly on other blockchain environments. Have fun!

And as I am a heavy user of "Minerva" and would like to mention it in a workshop next week (where Thomas will present it), it would be cool, if Minerva also displays icons and not just placeholders of presented NFTs. Having written that, I must admit, that my life does not depend on this ;-)

KR,
Chris

**Comment by chris2286266** [comment]
https://www4.baumann.at/blue-skies-en/

**Comment by seliqui** [comment]
Done :)

**Pull request merged**
